stages:
  - build-full
  - migrate_dev
  - deploy-full
  - build-back
  - deploy-back
  - migrate_main
  - build-front
  - deploy-front

# Dev: Migrate
dev_migrate:
  stage: migrate_dev
  image: python:3.12-slim-bookworm
  tags:
    - saas
  script:
    - |
      echo "Running dev migration..."
      mv .infra/.env_dev .env
    - chmod +x .infra/.ansible/inject_secrets.sh
    - .infra/.ansible/inject_secrets.sh
    - mv .env backend/.env && cd backend
    - pip install alembic sqlmodel python-dotenv psycopg2-binary pydantic "pydantic[email]" geoalchemy2 "bcrypt<4.0.0" "passlib[bcrypt]==1.7.4"
    - alembic upgrade head
    - python -m config.superadmin_scripts.seed_initial_data
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Main: Migrate
main_migrate:
  stage: migrate_main
  image: python:3.12-slim-bookworm
  tags:
    - saas
  script:
    - |
      echo "Running production migration..."
      mv .infra/.env_prod_back .env
    - chmod +x .infra/.ansible/inject_secrets.sh
    - .infra/.ansible/inject_secrets.sh
    - mv .env backend/.env && cd backend
    - sed -i  -e 's/postgres_gis/reclamos.reputacion.digital/g' .env
    - pip install alembic sqlmodel python-dotenv psycopg2-binary pydantic geoalchemy2
    - alembic upgrade head
    - python -m config.superadmin_scripts.seed_initial_data
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

# Dev: Build Back
dev_build_back:
  stage: build-full
  image: docker:latest
  tags:
    - saas
  services:
    - docker:dind
  before_script:
    - unset DOCKER_HOST
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - |
      source VERSION
      tag="$CI_COMMIT_REF_SLUG$VERSION"
      echo "Running on branch '$CI_COMMIT_BRANCH' -- tag = '$tag'"
    - cd backend
    - docker build -f Dockerfile --pull -t "$CI_REGISTRY/reclamo_ciudadano_back:$tag" .
    - docker push "$CI_REGISTRY/reclamo_ciudadano_back:$tag"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Dev: Build Front
dev_build_front:
  stage: build-full
  image: docker:latest
  tags:
    - saas
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - |
      source VERSION
      tag="$CI_COMMIT_REF_SLUG$VERSION"
      echo "Running on branch '$CI_COMMIT_BRANCH' -- tag = '$tag'"
    - cd frontend-rc
    - docker build -f Dockerfile --pull -t "$CI_REGISTRY/reclamo_ciudadano_front:$tag" .
    - docker push "$CI_REGISTRY/reclamo_ciudadano_front:$tag"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Dev: Deploy
dev_deploy:
  stage: deploy-full
  image: "ieferrari/ansible:11.0.0"
  tags:
    - saas
  script:
    - source VERSION
    - |
      echo "<<<< DEVELOPMENT DEPLOY >>>>"
      tag="$CI_COMMIT_REF_SLUG$VERSION"
      target_server="dev"
      folder_name="reclamo_ciudadano_dev"
      cat $ansible_credentials_yml_dev >> .infra/.ansible/cred.yml
      mv .infra/.env_dev .env
      mv docker-compose.dev.yml docker-compose.yml
    - chmod +x .infra/.ansible/inject_secrets.sh
    - .infra/.ansible/inject_secrets.sh
    - sed -i "s/IMAGE_VERSION=0*/IMAGE_VERSION=\"$tag\"/" .env
    - export ANSIBLE_CONFIG=$(pwd)/.infra/.ansible/ansible.cfg
    - ansible-playbook -i .infra/hosts .infra/.ansible/docker_remote_launch.yml --extra-vars "server_name=$target_server folder_name=$folder_name"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

# Main: Build Back
main_build_back:
  stage: build-back
  image: docker:latest
  tags:
    - saas
  services:
    - docker:dind
  before_script:
    - unset DOCKER_HOST
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - |
      source VERSION
      tag="$VERSION"
      echo "Running on branch '$CI_COMMIT_BRANCH' -- tag = '$tag'"
    - cd backend
    - docker build -f Dockerfile --pull -t "$CI_REGISTRY/reclamo_ciudadano_back:$tag" .
    - docker push "$CI_REGISTRY/reclamo_ciudadano_back:$tag"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

main_back_deploy:
  stage: deploy-back
  image: "ieferrari/ansible:11.0.0"
  tags:
    - saas
  script:
    - source VERSION
    - |
      echo "<<<< PRODUCTION BACKEND DEPLOY >>>>"
      tag="$VERSION"
      target_server="prod"
      folder_name="reclamo_ciudadano_back"
      cat $ansible_credentials_yml >> .infra/.ansible/cred.yml
      mv docker-compose.prod.back.yml docker-compose.yml
      mv .infra/.env_prod_back .env
    - chmod +x  .infra/.ansible/inject_secrets.sh 
    - .infra/.ansible/inject_secrets.sh
    - sed -i "s/IMAGE_VERSION=0*/IMAGE_VERSION=\"$tag\"/" .env
    - export  ANSIBLE_CONFIG=$(pwd)/.infra/.ansible/ansible.cfg
    - |
      ansible-playbook -i .infra/hosts .infra/.ansible/docker_remote_launch.yml --extra-vars "{\"server_name\": \"${target_server}\", \"folder_name\": \"${folder_name}\", \"services_list\": [\"backend\", \"traefik\", \"postgres_gis\"]}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

main_build_front:
  stage: build-front
  image: docker:latest
  tags:
    - saas
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - |
      source VERSION
      tag="$VERSION"
      echo "Running on branch '$CI_COMMIT_BRANCH' -- tag = '$tag'"
    - cd frontend-rc
    - cp ../.infra/.env_prod_front .env
    - sed -i "s/IMAGE_VERSION=0*/IMAGE_VERSION=\"$tag\"/" .env
    - sed -i "s/backend:8000/reclamos.reputacion.digital:8007/" .env
    - sed -i "s/SECRET_PROD_FRONTEND_API_KEY/$SECRET_PROD_FRONTEND_API_KEY/" .env
    - sed -i "s/SECRET_PROD_FRONTEND_API_CLIENT/$SECRET_PROD_FRONTEND_API_CLIENT/" .env
    - docker build --build-arg NODE_ENV=production -f Dockerfile --pull -t "$CI_REGISTRY/reclamo_ciudadano_front:$tag" .
    - docker push "$CI_REGISTRY/reclamo_ciudadano_front:$tag"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

main_front_deploy:
  stage: deploy-front
  image: "ieferrari/ansible:11.0.0"
  tags:
    - saas
  script:
    - source VERSION
    - |
      echo "<<<< PRODUCTION BACKEND DEPLOY >>>>"
      tag="$VERSION"
      target_server="prod"
      folder_name="reclamo_ciudadano_front"
      cat $ansible_credentials_yml >> .infra/.ansible/cred.yml
      mv docker-compose.prod.front.yml docker-compose.yml
      mv .infra/.env_prod_front .env
    - chmod +x  .infra/.ansible/inject_secrets.sh 
    - .infra/.ansible/inject_secrets.sh
    - sed -i "s/IMAGE_VERSION=0*/IMAGE_VERSION=\"$tag\"/" .env
    - export  ANSIBLE_CONFIG=$(pwd)/.infra/.ansible/ansible.cfg
    - |
      ansible-playbook -i .infra/hosts .infra/.ansible/docker_remote_launch.yml --extra-vars "{\"server_name\": \"${target_server}\", \"folder_name\": \"${folder_name}\"}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
