version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: ["python3", "app.py"]

  frontend:
    build:
      context: ./frontend-rc
      dockerfile: Dockerfile
    volumes:
      - ./frontend-rc:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./frontend-rc/.env
    command: ["npm", "run", "dev"]

volumes:
  node_modules:

