services:
  backend:
    image: registry.reputacion.digital/reclamo_ciudadano_back:${IMAGE_VERSION}
    volumes:
      - ./.env:/app/.env
    ports:
      - "8007:8000"
    depends_on:
      postgres_gis:
        condition: service_healthy
    command: ["python3", "app.py"]
    networks:
      - traefik-public

  traefik:
    image: traefik:v3.0
    ports:
      - 80:80
      - 443:443
      - 8888:8888
      - 8081:8081
    restart: always
    labels:
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.traefik-dashboard-http.middlewares=https-redirect=label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-public-certificates:/certificates
      - ./rules:/rules:ro
    command:
      - --providers.file=true
      - --providers.file.directory=rules
      - --providers.file.watch=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=ivanferrarigalizia@gmail.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
      - --metrics.prometheus=true
      - --entryPoints.metrics.address=:8888
      - --metrics.prometheus.entryPoint=metrics
    networks:
      - traefik-public

  postgres_gis:
    image: postgis/postgis:17-3.5
    container_name: postgres_gis
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PSWD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
