services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000" 
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app 
    command: ["python3", "app.py"]

  frontend:
    build:
      context: ./frontend-rc
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend-rc/.env
    volumes:
      - ./frontend-rc:/app
    command: ["npm", "run", "dev"]
