# List the tables that PostGIS or the TIGER extension create (and that
# you do NOT want Alembic to drop, since you don't actually manage them):
# alembic/postgis_tables.py

EXCLUDE_TABLES = {
    "pagc_lex",
    "addrfeat",
    "state_lookup",
    "loader_lookuptables",
    "cousub",
    "county",
    "zip_state_loc",
    "state",
    "loader_platform",
    "bg",
    "tract",
    "tabblock20",
    "countysub_lookup",
    "faces",
    "pagc_gaz",
    "secondary_unit_lookup",
    "pagc_rules",
    "zip_state",
    "geocode_settings",
    "place_lookup",
    "street_type_lookup",
    "place",
    "zip_lookup",
    "topology",
    "direction_lookup",
    "tabblock",
    "edges",
    "loader_variables",
    "zip_lookup_all",
    "addr",
    "county_lookup",
    "zcta5",
    "geocode_settings_default",
    "layer",
    "featnames",
    "zip_lookup_base",
}
