"""Add categories to ClaimTypes table

Revision ID: 176ff36b207b
Revises: b0bb9e2e8782
Create Date: 2025-01-07 18:18:16.788831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "176ff36b207b"
down_revision: Union[str, None] = "b0bb9e2e8782"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.bulk_insert(
        sa.table(
            "claimtypes",
            sa.column("category"),
            sa.column("description"),
        ),
        [
            {
                "category": "Lighting",
                "description": "Burned-out streetlights, insufficient lighting, damaged light poles.",
            },
            {"category": "Signage", "description": "Damaged or missing street signs."},
            {
                "category": "Sewage",
                "description": "Broken pipes, unpleasant odors, flooding.",
            },
            {
                "category": "Streets",
                "description": "Potholes, damaged or missing speed bumps, inadequate signage at intersections.",
            },
            {
                "category": "Sanitation",
                "description": "Debris, garbage, fallen trees, illegal dumping.",
            },
            {
                "category": "Public Safety",
                "description": "Theft, damage to public property, vandalism.",
            },
            {
                "category": "Public Health",
                "description": "Presence of disease vectors, pests, stray animals, standing water that could promote mosquito breeding.",
            },
            {
                "category": "Public Spaces",
                "description": "Lack of maintenance of plazas, green areas, playgrounds and public fountains.",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    claimtypes = sa.table("claimtypes", sa.column("category"))
    op.execute(
        claimtypes.delete().where(
            claimtypes.c.category.in_(
                [
                    "Lighting",
                    "Signage",
                    "Sewage",
                    "Streets",
                    "Sanitation",
                    "Public Safety",
                    "Public Health",
                    "Public Spaces",
                ]
            )
        )
    )
    # ### end Alembic commands ###
