"""Add has multimedia boolean in Claim record

Revision ID: 4abe5084b422
Revises: 784d892fc5e2
Create Date: 2025-01-28 12:30:22.969927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abe5084b422'
down_revision: Union[str, None] = '784d892fc5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('has_multimedia', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'has_multimedia')
    # ### end Alembic commands ###
