"""Add logical deletion fields and config

Revision ID: 68267bd5c2b6
Revises: 0d7213509b54
Create Date: 2025-01-22 17:30:03.549550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68267bd5c2b6'
down_revision: Union[str, None] = '0d7213509b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('claim', sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'deleted')
    op.drop_column('claim', 'deleted_at')
    # ### end Alembic commands ###
