"""Add file names array in Claim

Revision ID: a04a24f2d806
Revises: 4abe5084b422
Create Date: 2025-01-28 13:16:47.642423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a04a24f2d806'
down_revision: Union[str, None] = '4abe5084b422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('files', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'files')
    # ### end Alembic commands ###
