"""Add type_category_id FK to Claim table

Revision ID: b0bb9e2e8782
Revises: e2e646b8e633
Create Date: 2025-01-07 18:12:47.034037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b0bb9e2e8782"
down_revision: Union[str, None] = "e2e646b8e633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("claim", sa.Column("type_category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "claim", "claimtypes", ["type_category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "claim", type_="foreignkey")
    op.drop_column("claim", "type_category_id")
    # ### end Alembic commands ###
