"""Add public id in Clients

Revision ID: b19a7d8a4280
Revises: 6039ad802f27
Create Date: 2025-05-19 14:38:21.736881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b19a7d8a4280"
down_revision: Union[str, None] = "6039ad802f27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "clients",
        sa.Column(
            "public_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_clients_public_id"), "clients", ["public_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clients_public_id"), table_name="clients")
    op.drop_column("clients", "public_id")
    # ### end Alembic commands ###
