"""add admin_users table

Revision ID: dc6c2eaa0b23
Revises: db3ab79fd244
Create Date: 2025-05-23 12:12:40.684243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6c2eaa0b23'
down_revision: Union[str, None] = 'db3ab79fd244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'email', name='uq_user_email_per_client'),
    sa.UniqueConstraint('public_id')
    )
    op.drop_constraint('fk_claim_client', 'claim', type_='foreignkey')
    op.create_foreign_key(None, 'claim', 'clients', ['client_id'], ['id'])
    op.drop_constraint('uq_clients_name', 'clients', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_clients_name', 'clients', ['name'])
    op.drop_constraint(None, 'claim', type_='foreignkey')
    op.create_foreign_key('fk_claim_client', 'claim', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
