"""Change table name from reports to claims

Revision ID: e64e5965e86c
Revises: 892f022d2fd1
Create Date: 2025-01-06 17:24:53.921412

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e64e5965e86c"
down_revision: Union[str, None] = "892f022d2fd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "claim",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "claim_location",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_claim_claim_location",
        "claim",
        ["claim_location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )

    op.drop_constraint("multimedia_report_id_fkey", "multimedia", type_="foreignkey")
    op.add_column("multimedia", sa.Column("claim_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "multimedia", "claim", ["claim_id"], ["id"])
    op.drop_column("multimedia", "report_id")
    op.drop_geospatial_index(
        "idx_report_report_location",
        table_name="report",
        postgresql_using="gist",
        column_name="report_location",
    )
    op.drop_geospatial_table("report")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "multimedia",
        sa.Column("report_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "multimedia", type_="foreignkey")
    op.create_foreign_key(
        "multimedia_report_id_fkey", "multimedia", "report", ["report_id"], ["id"]
    )
    op.drop_column("multimedia", "claim_id")
    op.create_geospatial_table(
        "report",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "report_location",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
                _spatial_index_reflected=True,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "description", sa.VARCHAR(length=1024), autoincrement=False, nullable=False
        ),
        sa.Column(
            "status", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="report_pkey"),
    )
    op.create_geospatial_index(
        "idx_report_report_location",
        "report",
        ["report_location"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.drop_geospatial_index(
        "idx_claim_claim_location",
        table_name="claim",
        postgresql_using="gist",
        column_name="claim_location",
    )
    op.drop_geospatial_table("claim")
    # ### end Alembic commands ###
