"""Add public_id to Claim with proper UUID type

Revision ID: 0d7213509b54
Revises: 176ff36b207b
Create Date: 2025-01-14 16:49:17.304156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7213509b54'
down_revision: Union[str, None] = '176ff36b207b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('public_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_claim_public_id'), 'claim', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_public_id'), table_name='claim')
    op.drop_column('claim', 'public_id')
    # ### end Alembic commands ###
