"""Add deleted_at field in Claim Table

Revision ID: 11d36653ec82
Revises: 0d7213509b54
Create Date: 2025-01-22 16:39:06.335367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d36653ec82'
down_revision: Union[str, None] = '0d7213509b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'deleted_at')
    # ### end Alembic commands ###
