"""Change type on report_location model

Revision ID: 892f022d2fd1
Revises: e12fdd0fae60
Create Date: 2025-01-03 17:10:52.940144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892f022d2fd1'
down_revision: Union[str, None] = 'e12fdd0fae60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
