---
- hosts: "{{ server_name }}"
  vars_files:
    - cred.yml

  tasks:
    # ############################################
    # Log in into docker hub registry
    - name: log into docker hub registry
      docker_login:
        username: "{{ lookup('ansible.builtin.env','CI_REGISTRY_USER') }}"
        password: "{{ lookup('ansible.builtin.env','CI_REGISTRY_PASSWORD') }}"
        registry_url: "{{ lookup('ansible.builtin.env','CI_REGISTRY') }}"

    # ############################################
    # Create all the required folders
    - name: Creates directory structure
      file:
        path: "/opt/deploy/{{ folder_name }}"
        state: directory
      loop:
        - ""

    # ###############################################
    # Copy all the required files
    - name: Copy configuration files
      block:
        - name: Copy docker-compose file
          ansible.builtin.copy:
            src: ../../docker-compose.yml
            dest: "/opt/deploy/{{ folder_name }}/docker-compose.yml"
            owner: ansible_saas
            group: deploy
            mode: "0664"

        - name: Copy .env file
          ansible.builtin.copy:
            src: ../../.env
            dest: "/opt/deploy/{{ folder_name }}/.env"
            owner: ansible_saas
            group: deploy
            mode: "0664"

    # #############################################
    # Tear down, create and run docker services
    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: /opt/deploy/{{ folder_name }}/
        state: absent
        remove_orphans: true

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: /opt/deploy/{{ folder_name }}/
        pull: always
        services: "{{ services_list | default(omit) }}"
      register: output

    - name: Run `docker-compose up` again
      community.docker.docker_compose_v2:
        project_src: /opt/deploy/{{ folder_name }}/
        pull: never
        services: "{{ services_list | default(omit) }}"
      register: output


#ansible-playbook -i .ansible/hosts .ansible/docker_remote_launch.yml --extra-vars "server_name=$target_server folder_name=$folder_name"

#ansible-playbook -i .ansible/hosts .ansible/docker_remote_launch.yml --extra-vars "server_name=dev folder_name=reclamo_ciudadano"


